Do not try to set already active configuration when claiming an interface
This would provoke the exception below if another process has claimed
an interface of the device already hence this is needed to support different
processes accessing the same device (but different interfaces).

javax.usb.UsbPlatformException: libusb_set_configuration(): LIBUSB_ERROR_BUSY
	at javalibusb1.Libusb1UsbInterface.nativeSetConfiguration(Native Method)
	at javalibusb1.Libusb1UsbInterface.claim(Libusb1UsbInterface.java:40)